spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.20.234:3306/simple_file_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Yueqian8520@
    hikari:
          minimum-idle: 5
          maximum-pool-size: 15
          auto-commit: true
          idle-timeout: 30000
          pool-name: DatebookHikariCP
          max-lifetime: 120000
          connection-timeout: 30000
          connection-test-query: SELECT 1
  redis:
    database: 0
    host: 106.13.20.234
    port: 6379
    password:
    timeout: 5000

  jackson:
      property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      cache: false
      enabled: true